2020-07-08 06:47:22,820 ERROR: Exception on /reset_password_request [POST] [in /home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/auth/routes.py", line 58, in reset_password_request
    send_password_reset_email(user)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/auth/email.py", line 11, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2020-07-08 06:49:39,469 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:55]
2020-07-08 06:53:44,791 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:55]
2020-07-08 06:53:49,959 ERROR: Exception on /index [GET] [in /home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/routes.py", line 33, in index
    return render_template('index.html', title='Home', form=form,
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/templates/base.html", line 1, in top-level template code
    {% extends 'cbootstrap/base.html' %}
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: cbootstrap/base.html
2020-07-08 07:09:44,609 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:55]
2020-07-08 07:25:04,606 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:55]
2020-07-08 07:26:05,609 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:55]
